/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SavedTemplate {
  'id' : bigint,
  'name' : string,
  'scenario' : Scenario,
}
export interface Scenario {
  'defenders' : Array<string>,
  'priority' : string,
  'attackers' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], boolean>,
  'duplicateTemplate' : ActorMethod<[bigint, string], [] | [bigint]>,
  'getCallerTemplates' : ActorMethod<[], Array<SavedTemplate>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentScenario' : ActorMethod<[], [] | [Scenario]>,
  'getTemplate' : ActorMethod<[bigint], [] | [SavedTemplate]>,
  'getTemplateNames' : ActorMethod<[], Array<string>>,
  'getTemplatesByUser' : ActorMethod<[Principal], Array<SavedTemplate>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'renameTemplate' : ActorMethod<[bigint, string], boolean>,
  'saveCurrentScenario' : ActorMethod<[Scenario], undefined>,
  'saveTemplate' : ActorMethod<[string, Scenario], bigint>,
  'updateTemplate' : ActorMethod<[bigint, Scenario], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];