/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Scenario = IDL.Record({
  'defenders' : IDL.Vec(IDL.Text),
  'priority' : IDL.Text,
  'attackers' : IDL.Vec(IDL.Text),
});
export const SavedTemplate = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'scenario' : Scenario,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'duplicateTemplate' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'getCallerTemplates' : IDL.Func([], [IDL.Vec(SavedTemplate)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentScenario' : IDL.Func([], [IDL.Opt(Scenario)], ['query']),
  'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(SavedTemplate)], ['query']),
  'getTemplateNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTemplatesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SavedTemplate)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'renameTemplate' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'saveCurrentScenario' : IDL.Func([Scenario], [], []),
  'saveTemplate' : IDL.Func([IDL.Text, Scenario], [IDL.Nat], []),
  'updateTemplate' : IDL.Func([IDL.Nat, Scenario], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Scenario = IDL.Record({
    'defenders' : IDL.Vec(IDL.Text),
    'priority' : IDL.Text,
    'attackers' : IDL.Vec(IDL.Text),
  });
  const SavedTemplate = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'scenario' : Scenario,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'duplicateTemplate' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'getCallerTemplates' : IDL.Func([], [IDL.Vec(SavedTemplate)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentScenario' : IDL.Func([], [IDL.Opt(Scenario)], ['query']),
    'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(SavedTemplate)], ['query']),
    'getTemplateNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTemplatesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SavedTemplate)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'renameTemplate' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'saveCurrentScenario' : IDL.Func([Scenario], [], []),
    'saveTemplate' : IDL.Func([IDL.Text, Scenario], [IDL.Nat], []),
    'updateTemplate' : IDL.Func([IDL.Nat, Scenario], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };